In [7]:
# %pip install torch
# %pip install numpy

In [1]:
import torch

In [10]:
rand_sample = torch.rand(10000)
print("Rand sample:", rand_sample)
randn_sample = torch.randn(10000)
print("Randn sample:", randn_sample)
zeros_sample = torch.zeros(10)
print("Zeros sample:", zeros_sample)
ones_sample = torch.ones(10)
print("Ones sample:", ones_sample)
arange_sample = torch.arange(0, 10)
print("Arange sample:", arange_sample)
linspace_sample = torch.linspace(0, 10, steps=5)
print("Linspace sample:", linspace_sample)
eye_sample = torch.eye(5)
print("Indentity sample:", eye_sample)
empty_sample = torch.empty(10)
print("Empty sample:", empty_sample)

Rand sample: tensor([0.4624, 0.7603, 0.9325,  ..., 0.4845, 0.9213, 0.4519])
Randn sample: tensor([-1.4773,  1.0664, -0.2764,  ...,  1.2009,  0.5726, -0.0119])
Zeros sample: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Ones sample: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
Arange sample: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Linspace sample: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Indentity sample: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Empty sample: tensor([0.0000, 1.8750, 0.0000, 1.8750, 0.0000, 1.8750, 0.0000, 1.8750, 0.0000,
        1.8750])


In [11]:
# Basic Arithmetic Operations
x = torch.tensor([5.0, 2.0, 4.0])
y = torch.tensor([2.0, 1.0, 3.0])

print(x+y)
print(x*y)
print(x@y) # vector dot product
# aggregations
print(x.sum())
print(x.mean())
print(x.max())

tensor([7., 3., 7.])
tensor([10.,  2., 12.])
tensor(24.)
tensor(11.)
tensor(3.6667)
tensor(5.)


In [13]:
# Activation Functions
import torch.nn.functional as F
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
# relu - sets negative values to 0
print(F.relu(x))
# sigmoid - normalises values between 0 and 1
print(F.sigmoid(x))
# tanh - normalises values between -1 and 1
print(F.tanh(x))

tensor([0., 0., 0., 1., 2.])
tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])


In [ ]:
x = torch.tensor(3.0, requires_grad=True) # enable gradient tracking
f = x**2
# .backward() -> calculates gradient using backpropagation
f.backward()
# check gradient(derivative) at point x
print(x.grad)

tensor(6.)
